Improved healthcareElementId management
icure/icure-medical-device-js-sdk pull request #39
Opened 2022-09-30 15:44 UTC by TestaDiRapa

2022-09-30 16:22 UTC, aduchate requested changes

2022-09-30 16:22 UTC, aduchate commented on test/apis/healthcare-element-api.ts
> +  it('if no healthcareElement is specified, then it should be set to the Healthcare Element id', async () => {
```suggestion
  it('if no Healthcare Element healthcareElementId is specified, then it should be set to the Healthcare Element id', async () => {
```

2022-09-30 16:22 UTC, aduchate commented on test/apis/healthcare-element-api.ts
> +    expect(newHE.id).to.eq(newHE.healthcareElementId)
They might both be undefined... An extra expect ?

2022-10-03 08:32 UTC, lisatr2812 reviewed
I'm wondering why putting the id of the healthElement as a default value of the healthcareElementId. 
healthcareElementId links to a previous version of the healthcareElement. Putting the default value as the current id seems contradictory with that definition for me. 
I can see it as defining the first element of the healthcare elements chain, which makes sense. But then, I would not put the healthcareElementId as optional. 
We need to define what we prefer.

2022-10-03 09:32 UTC, lisatr2812 approved these changes

2022-10-03 09:32 UTC, merged